### ISSUE TITLE
DB: final_phase.sqf not execute after restart

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#25]
If all hideout are destroy.
Final phase is execute
Game save in DB.
Server restart.
All hideout are destroy.
But the final phase is not execute ([] execVM "core\fnc\common\final_phase.sqf";)

FIX : 
Add line : 
if (count btc_hideouts == 0) then {[] execVM "core\fnc\common\final_phase.sqf";};
in the load.sqf

**Comment by Giallustio** [comment]
https://github.com/Giallustio/HeartsAndMinds/commit/a9dd6b5585f73ddf029afa07ac4b9bf98d3d1ca1
