### ISSUE TITLE
DB : logistic object disappear

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#27]
Logistic object like fortifications are very cool to use and play with.
But after restart, logistic object from logistic point used to create little base around are not spawning.

Do you think you could make it persistant with DB ?

**Comment by Giallustio** [comment]
They should be, are you using the last version of github?

**Comment by Vdauphin** [comment]
Yep :/

**Comment by Giallustio** [comment]
I'll check it. Do you spawn them at the logistic point?

**Comment by Vdauphin** [comment]
Yes I will check too

**Comment by Vdauphin** [comment]
I tested again and for me it is not working :/

**Comment by Vdauphin** [comment]
FOB is here, hideout are all destroy but fortification are not here after save / restart

**Comment by Giallustio** [comment]
Tested on my dedi and it's working

**Comment by Vdauphin** [comment]
I tested  on a dedicate from a friend and yes it work.
But, I don't know why, it is not working on my dedicate (server.nitrado.net), do you know where the database is physically saved ?

**Comment by Giallustio** [comment]
server's profile
