### ISSUE TITLE
Final Phase : btc_fnc_city_set_clear not execute on dedicate

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#28]
When all hideout are destroyed, final phase run.
If the player clear a city, the circle marker red isn't green after clean city.

May be the btc_fnc_city_set_clear is not execute on dedicate server.

**Comment by Vdauphin** [comment]
Do you see on your dedicate the same issue ?

**Comment by Giallustio** [comment]
i've to test it

**Comment by Vdauphin** [comment]
Just did some test on my dedicate and now with a new database the issue is resolve :+1:
