### ISSUE TITLE
Civ spawn bug

### ISSUE THREAD

**Issue by Giallustio** [Giallustio/HeartsAndMinds#37]
Server keeps spawn civilian traffic even if the maximum is reached

**Comment by Vdauphin** [comment]
My first test :
        The bug appear in Editor too : 
         Start play the mission.
         Go in city
         vehicule traffic increase and stop when btc_civ_veh_active =5 (define in mission.sqf)
         if you destroy a civilian vehicule in traffic for some reason btc_civ_veh_active is equal to -23 

Bug :
btc_civ_veh_active is not correctly increment ==> misison keeps spawn civilian traffic

**Comment by Giallustio** [comment]
Found it!
EH fires multiple times!

**Comment by Vdauphin** [comment]
I just see it too :)
You are the best ! ;)

**Comment by Giallustio** [comment]
there are still few issues, for example if the driver leaves the vehicle or get killed, if the vehicle get stucked somewhere and so on, but i don't have time atm.

**Comment by Vdauphin** [comment]
I am testing your fix and for me the issue is not resolved ...

**Comment by Vdauphin** [comment]
Instead of https://github.com/Giallustio/HeartsAndMinds/commit/4d5aef53957883c22fc3e24c3f9059f646d11826, I am proposing an other fix : https://github.com/Giallustio/HeartsAndMinds/pull/38
