### ISSUE TITLE
AddActions called from EH post init is local

### ISSUE THREAD

**Issue by Giallustio** [Giallustio/HeartsAndMinds#46]

**Comment by Vdauphin** [comment]
I am not familiar with EH post init, I just know Post init and initpost exist but nothing more.

**Comment by Vdauphin** [comment]
Why do you prefer use it instead of addaction.sqf (https://github.com/Giallustio/HeartsAndMinds/blob/f83f7066287dfd11d9d72d48f08c7f3e08b31f20/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf)

**Comment by Giallustio** [comment]
Because in this way every unit spawned, even with zeus, is inside the system

**Comment by Giallustio** [comment]
(If it works)

:D

**Comment by Giallustio** [comment]
it doesn't work on server, just in editor. I'm waiting for an answer from ace team

**Comment by Giallustio** [comment]
rhs bugs xeh init, removed
