### ISSUE TITLE
Can't quit re-deploy dialog

### ISSUE THREAD

**Issue by Giallustio** [Giallustio/HeartsAndMinds#49]

**Comment by Vdauphin** [comment]
I saw it. 
Before you could select Base so if you select re-deploy dialog by mistake you could redeploy at base...

**Comment by Vdauphin** [comment]
What happen if you close the dialog with ESC ? 
https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/fnc/fob/redeploy.sqf#L31

**Comment by Giallustio** [comment]
I think you can't because i've added an EH to prevent it, I can't remember exactly, I've to look at the code when i get some time. It should be very very easy to fix.

I'm trying to make the curator eh to fire at the moment but i can't at all. Do you know why?
https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf

**Comment by Vdauphin** [comment]
I don't know what you are going to do but becareful with curator : "curator object is local and will be executed only where curator is local (on computer of player who's in control of it). "
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#CuratorObjectPlaced

**Comment by Giallustio** [comment]
I know it's local, but the point is that it doesn't fire anywhere...at least for me...i can't understand where i'm wrong

**Comment by Vdauphin** [comment]
Your error is in the compile.sqf

**Comment by Vdauphin** [comment]
https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/fnc/compile.sqf

**Comment by Giallustio** [comment]
It could be...same error i did in the past! I'll check it later! Thank you

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/commit/2cf05e90d58d439b6d513fd54d60d084f3c1baa4

**Comment by Vdauphin** [comment]
Just missing the .sqf extension !!! ;)
