### ISSUE TITLE
Respawn Helo not working

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#52]
I don't understand why in local (editor) the helo is respawning every time but not on dedicate.
My first explanation was the addEvenHandler not fired for some reason.

But I found this little post here : https://forums.bistudio.com/topic/181571-custom-vehicle-respawn-not-working-why/

Larrow said about eventHandler : "This is the problem, using Killed, even though the Wiki says 'will fire where the vehicle is local' when a player enters the vehicle it becomes local to them, only trouble is the eventHandler does not go with it. You will have to use MPKilled instead." He gived a little mission to test and explain the problem https://dl.dropboxusercontent.com/u/96095460/ARMA3/MP_EH_Killed_test.VR.zip

**Comment by Giallustio** [comment]
it still doesn't working on the last update?

**Comment by Vdauphin** [comment]
which update ?

**Comment by Giallustio** [comment]
yours :D

I will try to switch to MPkilled

**Comment by Vdauphin** [comment]
Oh sorry, nop x) I understood after that the addevenhandler doesn't work ^^

**Comment by Giallustio** [comment]
Ok np! If i understood this correctly the killed eh is bugged and fires locally IF the vehicle is local at that moment. So i've to move the fnc in the common side and check if is the server or the client,

**Comment by Vdauphin** [comment]
Yes correct !

**Comment by Giallustio** [comment]
i will fix it asap

**Comment by Vdauphin** [comment]
Thx ! :+1:

**Comment by Giallustio** [comment]
I've tried to fix it, but i can't run A3 at the moment, could you test it for me?

https://github.com/Giallustio/HeartsAndMinds/commit/b5570082e4193602162eb2b9f1683b37669a4ed8

**Comment by Vdauphin** [comment]
Yes !

**Comment by Giallustio** [comment]
Thank you!

**Comment by Vdauphin** [comment]
https://github.com/Giallustio/HeartsAndMinds/commit/b5570082e4193602162eb2b9f1683b37669a4ed8 : It works ! Good job :)

**Comment by Vdauphin** [comment]
https://github.com/Giallustio/HeartsAndMinds/commit/b5570082e4193602162eb2b9f1683b37669a4ed8 : The addMPEventHandler "MPKilled" isn't fired when you land on water ... The vehicule is killed but the EH isn't fired by :-1:  Arma 3 :-1: 
http://feedback.arma3.com/view.php?id=26503

**Comment by Giallustio** [comment]
Nice :D
