### ISSUE TITLE
Question: Submarine classe name

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#70]
Do you know an easy way to test if a vehicle is a submarine ? (usefull here https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/fnc/mil/patrol_create.sqf#L78)
Thx !

**Comment by Giallustio** [comment]
I've to look! I'll let you know

**Comment by Vdauphin** [comment]
I don't understand a lot with CfgVehicles. I understood that vehicles are in "familly" but in my case I can't identify the "familly".
e.g : I can't find the cfgvehicules for submarine : https://community.bistudio.com/wiki/ArmA:_CfgVehicles  
I tested some code to identify the classe name of all submarine, exemples :
typeof cursorTarget = "B_SDV_01_F"
 cursorTarget isKindOf "Ship" = true
But others ship are include in "Ship" :/

I hope it is clear ^^ (! Happy New Year !)

**Comment by Giallustio** [comment]
Did you try to take a look at the cfg viewer?

Okay, maybe i found something useful for you!

You can check the "simulation" of the vehicle, submarines use "submarinex"

Happy new year!

**Comment by Vdauphin** [comment]
Thx !
