### ISSUE TITLE
Respawn/Hook RHS_AH64D and RHS_UH1Y_d

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#71]
The RHS_AH64D and RHS_UH1Y_d don't respawn (https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/init_server.sqf#L13) and can't be hook (https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf#L30).
Is it normal ?

**Comment by Giallustio** [comment]
They shouldn't respawn, you have to repair them in base. You should be able to lift the wreck

**Comment by Vdauphin** [comment]
Correct ! 
May be adding something in the doc could be cleaner ?
(I was moving around the heli for so long time before I understood that heli can't be hook x) )

**Comment by Giallustio** [comment]
Indeed! I could make it even hook-able but propably it's better not

**Comment by Vdauphin** [comment]
Don't change that, it is "realistic" ! The player will look in documentation if he wants more information.

**Comment by Giallustio** [comment]
Great!
