### ISSUE TITLE
Tweak: Number of civ traffic

### ISSUE THREAD

**Issue by Vdauphin** [Giallustio/HeartsAndMinds#90]
With the new traffic https://github.com/Giallustio/HeartsAndMinds/pull/83 civ behavior, we saw less civ traffic.
I tested `btc_civ_max_veh = 20` and it works well (https://github.com/Giallustio/HeartsAndMinds/blob/master/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis/core/def/mission.sqf#L140).
May be increase `btc_civ_max_veh` to `15` could be a solution ?

**Comment by Giallustio** [comment]
Tweaked https://github.com/Giallustio/HeartsAndMinds/commit/aab092316cea90322057fa16f50843a6f6820e2b
